services:
  infinidat_app:
    build: .
    container_name: infinidat_app
    ports:
      - "5000:5000"
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      DEBUG: "false"
      DB_PATH: /data/db.sqlite3
    volumes:
      - ./data:/data
    restart: unless-stopped

  infinidant_prometheus:
    image: prom/prometheus:latest
    container_name: infinidat_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - infinidant_app
    restart: unless-stopped
